flaskr/views.py
import datetime
import time
from flask import(
    Blueprint, abort, request, render_template,
    redirect, url_for, flash, session, jsonify
)
from flask_login import (
    current_user, login_user, logout_user,
    login_required
    )
from itsdangerous import json
from sqlalchemy import false, true
from flaskr.models import (
    Task, User, PasswordResetToken, 
    Company, Company_basic, Company_step,
    Event, Company_number, EventSec
)
from flaskr import db

from flaskr.forms import (
    LoginForm, RegisterForm, ResetPasswordForm,
    UserForm, ChangePasswordForm, CompanyForm,
    CompanySearchForm, toDoForm, TaskDoneForm,
    BasicCompanyForm, BasicCompanyStepFrom,
    EventForm, CalendarForm, BasicCompanyNumberFrom,
    BasicCompanyEditForm
)

# ブループリントはアプリを分割できる＝プログラムの保守性を向上
bp = Blueprint('app', __name__, url_prefix='') #第一引数はbpの名前、第二引数はbpのパッケージ名、第三引数はアプリのルートパス

@bp.route('/') #htmlへのパスは「Blueprintの引数で指定した url_prefix」+ 「@Blueprintインスタンス.route('パス')」
def home():
    return render_template('home.html')

#登録画面
@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            email = form.email.data,
            username = form.username.data
        )
        #ユーザー名とメールアドレスを登録
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()

        #パスワードの設定
        token = ''
        with db.session.begin(subtransactions=True):
            token = PasswordResetToken.publish_token(user)
        db.session.commit()
        #本当はメールに飛ばすほうが良い、ユーザーの登録したメールアドレスが正しいことが確認できる
        print(
            f'パスワード設定用URL: http://127.0.0.1:5000/reset_password/{token}'
            )
        flash('パスワード設定用のURLを送りました。ご確認ください')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)

# flask_loginの機能で簡単にログイン・ログアウトを管理できる
@bp.route('/logout')
def logout():
    logout_user() #ログアウト
    return redirect(url_for('app.home')) #ログアウトしたらホームに飛ばす

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_email(form.email.data)
        if user and user.is_active and user.validate_password(form.password.data): #ユーザーが検索されたか、ユーザーがアクティブか、パスワードがあっているか
            login_user(user, remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        elif not user:
            flash('存在しないユーザーです')
        elif not user.is_active:
            flash('無効なユーザーです。パスワードを再設定してください')
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードの組み合わせが誤っています')
    return render_template('login.html', form=form)

#パスワード設定用URLの作成
@bp.route('/reset_password/<uuid:token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm(request.form)
    #tokenに紐づいたユーザIDを得て、そのユーザIDでパスワードを設定する
    reset_user_id = PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method == 'POST' and form.validate():
        password = form.password.data
        #ユーザIDからユーザーテーブルからレコード（インスタンス）を取得
        user = User.select_user_by_id(reset_user_id)
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードを更新しました')
        return redirect(url_for('app.login'))
    return render_template('reset_password.html', form=form)

# ユーザーを削除する
@bp.route('/delete')
def delete():
    # 今ログインしているユーザのID取得
    user_id = current_user.get_id()
    # ユーザのインスタンス取得
    user = User.select_user_by_id(user_id)
    # 削除
    with db.session.begin(subtransactions=True):
        user.delete_user(user_id)
    db.session.commit()
    flash('ユーザーを削除しました')
    return redirect(url_for('app.login'))

# ユーザーの情報を編集する
@bp.route('/user', methods=['GET', 'POST'])
@login_required #ログインしていないと見れないデコレータ⇒flask_loginでログインを管理しているためできる
def user():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        #今ログインしているユーザのインスタンス取得
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            #名前の変更反映
            user.username = form.username.data
            #メールアドレスの変更反映
            user.email = form.email.data
        db.session.commit()
        flash('ユーザ情報の更新に成功しました')
    return render_template('user.html', form=form)

@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_id(current_user.get_id())
        password = form.password.data
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
        db.session.commit()
        flash('パスワードの更新に成功しました')
        return redirect(url_for('app.user'))
    return render_template('change_password.html', form=form)

# 会社名前の検索(将来的には会社名や志望度などで分岐)
@bp.route('/cp_data/<op>', methods=['GET', 'POST'])
@login_required
def cp_data(op):
    form = CompanySearchForm(request.form)
    companies = None
    # フォームからgetメソッドでとってきている
    comname = request.args.get('comname', "", type=str)
    # メソッドをgetにすることで今どのページにいるかわかるらしい(ページネーション機能は未定)
    if comname:
        companies = Company.search_by_comname(comname, current_user.get_id())
    else:
        companies = Company.select_company_by_user_id(current_user.get_id())
    return render_template(
        'cp_data.html', form=form, companies=companies,
        comname=comname
    )
    

@bp.route('/cp_reg', methods=['GET', 'POST'])
@login_required
def cp_reg():
    form = CompanyForm(request.form)
    if request.method == 'POST' and form.validate():
        company = Company(
            from_user_id = current_user.get_id(),
            comname = form.comname.data,
            wishpoint = form.wishpoint.data,
            step = form.step.data,
            scale = form.scale.data,
            startmoney = form.startmoney.data,
            numemploy = form.numemploy.data,
            comment = form.comment.data
        )
        with db.session.begin(subtransactions=True):
            company.create_new_company()
        db.session.commit()
        flash('会社を登録しました。')
        return redirect(url_for('app.cp_reg'))
    return render_template('cp_reg.html', form=form)

@bp.route('/cp_edit/<id>', methods=['GET', 'POST'])
@login_required
def cp_edit(id):
    form = CompanyForm(request.form)
    company = Company.select_company_by_id(id)
    if request.method == 'POST' and form.validate():
        with db.session.begin(subtransactions=True):
            company.comname = form.comname.data
            company.wishpoint = form.wishpoint.data
            company.step = form.step.data
            company.scale = form.scale.data
            company.startmoney = form.startmoney.data
            company.numemploy = form.numemploy.data
            company.comment = form.comment.data
        db.session.commit()
        flash('会社の情報の更新に成功しました')
    return render_template(
        'cp_edit.html', company=company,
        form=form
    )

# 会社の情報削除
@bp.route('/cp_del/<id>')
@login_required
def cp_del(id):
    # ユーザのインスタンス取得
    company = Company.select_company_by_id(id)
    # 削除
    with db.session.begin(subtransactions=True):
        company.delete_company(id)
    db.session.commit()
    flash('会社情報を削除しました')
    return redirect(url_for('app.cp_data'))

# 会社名前の検索(将来的には会社名や志望度などで分岐)
# bp.route('/company_search')
# @login_required
# def company_search():
#     form = CompanySearchForm(request.form)
#     session['url'] = 'app.company_search'
#     companies = None
#     # フォームからgetメソッドでとってきている
#     comname = request.args.get('comname', None, type=str)
#     # メソッドをgetにすることで今どのページにいるかわかるらしい(ページネーション機能は未定)
#     if comname:
#         companies = Company.search_by_comname(comname, current_user.get_id())

#     return render_template('cp_data.html', form=form, companies=companies)

# todoリストのホーム画面
@bp.route('/toDo_home', methods=['GET', 'POST'])
@login_required
def toDo_home():
    # この関数に戻ってくるためにセッションの登録
    # session['url'] = 'app.toDo_home'
    # 完了処理、別画面から完了する場合は別関数を作成する
    form = TaskDoneForm(request.form)
    if request.method == 'POST':
        task = Task.select_task_by_id(form.task_id.data)
        with db.session.begin(subtransactions=True):
            task.update_status()
        db.session.commit()
    tasks = Task.select_active_task_by_user_id(current_user.get_id())
    return render_template(
        'toDo_home.html', tasks=tasks,
        form=form, check=False
    )

# todoリストのホーム画面(sortバージョン)
@bp.route('/toDo_home_sort', methods=['GET', 'POST'])
@login_required
def toDo_home_sort():
    # この関数に戻ってくるためにセッションの登録
    # session['url'] = 'app.toDo_home'
    # 完了処理、別画面から完了する場合は別関数を作成する
    form = TaskDoneForm(request.form)
    if request.method == 'POST':
        task = Task.select_task_by_id(form.task_id.data)
        with db.session.begin(subtransactions=True):
            task.update_status()
        db.session.commit()
    tasks = Task.select_active_task_by_user_id_sort(current_user.get_id())
    return render_template(
        'toDo_home.html', tasks=tasks,
        form=form, check=False
    )

# todoリストの一部表示
@bp.route('/toDo_home2', methods=['GET', 'POST'])
@login_required
def toDo_home2():
    form = TaskDoneForm(request.form)
    if request.method == 'POST':

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
    <dd>
        {{ field(**kwargs) | safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flaskr/templates/_subHeader.html
<div class="row">
    {% if current_user.is_authenticated %}
    <!-- <div class="col">
        <a href="{{url_for('app.cp_data', op='def')}}" class="mx-auto btn btn-success">企業データの閲覧</a>
    </div>
    <div class="col">
        <a href="{{url_for('app.cp_reg')}}" class="mx-auto btn btn-success">企業分析の登録</a>
    </div> -->
    <div class="col">
        <a href="{{url_for('app.home')}}" class="mx-auto btn btn-info">ホームへ</a>
    </div>
    <div class="col">
        <a href="{{ url_for('app.calendar') }}" class="mx-auto btn btn-success">予定表</a>
    </div>
    <div class="col">
        <a href="{{url_for('app.toDo_home')}}" class="mx-auto btn btn-info">ToDOリストへ</a>
    </div>
    <!-- <div class="col">
        <a href="{{url_for('app.basic_company')}}" class="mx-auto btn btn-success">企業基本情報</a>
    </div>
    <div class="col">
        <a href="{{url_for('app.basic_company_reg')}}" class="mx-auto btn btn-success">企業基本情報登録</a>
    </div>
    <div class="col">
        <a href="{{url_for('app.basic_company_number')}}" class="mx-auto btn btn-dark">企業数値比較</a> -->
    <!-- </div> -->
    {% endif %}
</div>

flaskr/templates/base_before.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}FLASK SNS{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='css/style.css') }}"></script>
        {% block a_js %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('app.home')}}">
                ホーム
            </a>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('app.logout')}}">
                ログアウト
            </a>
            <a class="navbar-brand" href="{{url_for('app.user')}}">
                ユーザ情報編集
            </a>
            <a class="navbar-brand" href="{{url_for('app.delete')}}">
                アカウント削除
            </a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('app.login')}}">
                ログイン
            </a>
            <a class="navbar-brand" href="{{url_for('app.register')}}">
                登録
            </a>
            {% endif %}
        </nav>
        <div class="container">
            <div class="row">
                <img class="img-fluid mx-auto" src="../static/bg/bg_1.jpg" alt="背景">
            </div>
            <div class="row mt-4" style="height: 100vh;">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        {% block b_js %}{% endblock %}
    </body>
    <footer class="footer mt-2">
        <div class="container" style="text-align: center;">
            <p class="text-muted">Copyright © ○○○○ All Rights Reserved..</p>
        </div>
    </footer>
</html>

flaskr/templates/basic_company.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業まとめ閲覧 - {{ super() }}
{% endblock %}

{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">会社の企業研究閲覧ページ</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row mt-3">
        <table class="table table-bordered">
            <thead>
                <td>会社の名前</td>
                <td>職種</td>
                <td>設立</td>
                <td>規模感</td>
                <td>株式公開</td>
                <td>主要取引先</td>
                <td>顧客</td>
                <td></td>
            </thead>
            <tbody>
                {% for company in basic_companies %}
                <tr>
                    <td><a href="{{ url_for('app.basic_company_edit', id=company.id) }}">{{ company.comname }}</a></td>
                    <td>{{ company.occupation }}</td>
                    <td>{{ company.length.strftime('%Y年') }}</td>
                    <td>{{ company.scale }}</td>
                    <td>{{ company.comstock }}</td>
                    <td>{{ company.supplier }}</td>
                    <td>{{ company.client }}</td>
                    <td><a href="{{ url_for('app.basic_company_desc', id=company.id) }}"><img src="../static/bg/dec.png" alt="{{company.id}}" style="height: 30px;"></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

flaskr/templates/basic_company_number.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業まとめ閲覧 - {{ super() }}
{% endblock %}

{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">会社の企業研究閲覧ページ</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row mt-3">
        <table class="table table-bordered">
            <thead>
                <td>会社の名前</td>
                <td>企業年齢</td>
                <td>資本金</td>
                <td>従業員数</td>
                <td>離職率</td>
                <td>初任給</td>
                <td>平均年収</td>
                <td></td>
            </thead>
            <tbody>
                {% for company in basic_companies %}
                {% set com_loop = loop %}
                <tr>
                    <td><a href="{{ url_for('app.basic_company_number_edit', comname=company.comname) }}">{{ company.comname }}</a></td>
                    {% for age in ages %}
                        {% if loop.index == com_loop.index %}
                            <td>{{ age }}年</td>
                        {% endif %}
                    {% endfor %}
                    <td>{{ company.capital }}</td>
                    <td>{{ company.employee }}</td>
                    <td>{{ company.turnover }}</td>
                    <td>{{ company.start_salary }}</td>
                    <td>{{ company.average_salary }}</td>
                    <td><a href="{{ url_for('app.basic_company_desc', id=company.id) }}"><img src="../static/bg/dec.png" alt="{{company.id}}" style="height: 30px;"></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更画面 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flaskr/templates/cp_data.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業まとめ閲覧 - {{ super() }}
{% endblock %}
{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">会社の企業研究閲覧ページ</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row">
        <form method="GET">
            {{ form.csrf_token }}
            {{ render_field(form.comname, value=comname) }}
            {{ form.submit() }}
        </form>
    </div>
    <div class="row mt-3">
        <table class="table table-bordered">
            <thead>
                <td>会社の名前</td>
                <td>志望度</td>
                <td>選考段階</td>
                <td>規模感</td>
                <td>資本金</td>
                <td>従業員数</td>
                <td>コメント</td>
            </thead>
            <tbody>
                {% for company in companies %}
                <tr>
                    <td><a href="{{ url_for('app.cp_edit', id=company.id) }}">{{ company.comname }}</a></td>
                    <td>{{ company.wishpoint }}</td>
                    <td>{{ company.step }}</td>
                    <td>{{ company.scale }}</td>
                    <td>{{ company.startmoney|money_format }}</td>
                    <td>{{ company.numemploy }}</td>
                    <td>{{ company.comment }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

flaskr/templates/cp_edit.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業情報編集 - {{ super() }}
{% endblock %}

{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">会社の情報編集</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row pl-3">
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.from_user_id(value=from_user_id) }}
            {{ render_field(form.comname, value=company.comname) }}
            {{ render_field(form.wishpoint, value=company.wishpoint) }}
            {{ render_field(form.step) }}
            {{ render_field(form.scale, value=company.scale) }}
            {{ render_field(form.startmoney, value=company.startmoney) }}
            {{ render_field(form.numemploy, value=company.numemploy) }}
            {{ render_field(form.comment, cols="50", rows="5", id='comment') }}
            {{ form.submit() }}
        </form>
    </div>

    <a class="float-right" href="{{url_for('app.cp_del', id=company.id)}}">会社情報の削除</a>
</div>
{% endblock %}

{% block b_js %}
<script type="text/javascript">
    let textarea = document.getElementById('comment')
    //エラーは無視して大丈夫
    textarea.value = {{company.comment|tojson}}
    // セレクターの作成
    let step_selector = "option[value="+{{company.step|tojson}}+"]";
    // セレクトのチェックをつける
    let step = document.getElementById("step").querySelector(step_selector).setAttribute("selected", "selected");
</script>
{% endblock %}

flaskr/templates/cp_reg.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業情報登録 - {{ super() }}
{% endblock %}
{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">会社の登録ページ</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row pl-3">
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.from_user_id(value=from_user_id) }}
            {{ render_field(form.comname) }}
            {{ render_field(form.wishpoint) }}
            {{ render_field(form.step) }}
            {{ render_field(form.scale) }}
            {{ render_field(form.startmoney) }}
            {{ render_field(form.numemploy) }}
            {{ render_field(form.comment, cols="50", rows="5") }}
            {{ form.submit() }}
        </form>
    </div>
</div>
{% endblock %}

flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}
ホーム - {{ super() }}
{% endblock %}
{% block content %}
<div class="col-3 border rounded pt-2">
    {% if current_user.is_authenticated %}
    <!-- <div class="row">
        <a href="{{url_for('app.cp_data', op='def')}}" class="mx-auto btn btn-success" style="width: 200px;">企業データの閲覧</a>
    </div>
    <div class="row">
        <a href="{{url_for('app.cp_reg')}}" class="mx-auto mt-2 btn btn-success" style="width: 200px;">企業分析の登録</a>
    </div> -->
    <div class="row">
        <a href="{{url_for('app.toDo_home')}}" class="mx-auto mt-2 btn btn-info" style="width: 200px; ">ToDOリストへ</a>
    </div>
    <div class="row">
        <a href="{{ url_for('app.calendar') }}" class="mx-auto btn mt-2 btn-success" style="width: 200px;">予定表</a>
    </div>
    <!-- <div class="row">
        <a href="{{url_for('app.basic_company')}}" class="mx-auto mt-2 btn btn-info" style="width: 200px; ">企業基本情報</a>
    </div>
    <div class="row">
        <a href="{{url_for('app.basic_company_reg')}}" class="mx-auto mt-2 btn btn-info" style="width: 200px; ">企業基本情報登録</a>
    </div> -->
    {% endif %}
</div>
<div class="col-8 offset-1 border rounded">
    <div class="row">
        {% if current_user.is_authenticated %}
        <div class="mx-auto mt-5">
            <p>ユーザ名: {{ current_user.username }}</p>
            <p>メールアドレス: {{ current_user.email }}</p>
        </div>
        {% else %}
            <div class="mx-auto">
                <p>ログイン or 登録をしてください</p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ログイン - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<div class="row ml-5">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flaskr/templates/toDo_edit.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
タスク編集 - {{ super() }}
{% endblock %}

{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">タスクの情報編集</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row pl-3">
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.from_user_id(value=from_user_id) }}
            {{ render_field(form.taskname, value=task.taskname) }}
            {{ render_field(form.workday, id='workday') }}
            {{ render_field(form.overday, id='overday') }}
            {{ render_field(form.memo, cols="50", rows="5", id='memo') }}
            {{ form.submit() }}
        </form>
    </div>

    <a class="float-right" href="{{url_for('app.toDo_del', id=task.id)}}">タスクの削除</a>
</div>
{% endblock %}

{% block b_js %}
<script type="text/javascript">
    let textarea = document.getElementById('memo')
    //エラーは無視して大丈夫
    textarea.value = {{task.memo|tojson}}

    // 日付の形式は、『YYYY-MM-DD』である必要がある
    let workday = document.getElementById('workday')
    workday.value = {{task.workday.strftime('%Y-%m-%d')|tojson}}
    let overday = document.getElementById('overday')
    overday.value = {{task.overday.strftime('%Y-%m-%d')|tojson}}
</script>
{% endblock %}

flaskr/templates/toDo_reg.html
{% from "_formhelpers.html" import render_field %}
{% extends "base_after.html" %}
{% block title %}
企業情報登録 - {{ super() }}
{% endblock %}
{% block content_after %}
<div class="col border rounded">
    <div class="row">
        <h1 class="mx-auto mt-3">タスクの登録ページ</h1>
    </div>
    {% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    <div class="row pl-3">
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.from_user_id(value=from_user_id) }}
            {{ render_field(form.taskname) }}
            {{ render_field(form.workday) }}
            {{ render_field(form.overday) }}
            {{ render_field(form.memo, cols="50", rows="5") }}
            {{ form.submit() }}
        </form>
    </div>
</div>
{% endblock %}